name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: windows
            arch: x64
          - os: macos-latest
            platform: macos
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        python build_executable.py

    - name: Create archive (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        cd release/${{ matrix.platform }}-${{ matrix.arch }}
        tar -czf ../../resumemind-cli-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz *

    - name: Create archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd release/${{ matrix.platform }}-${{ matrix.arch }}
        7z a ../../resumemind-cli-${{ matrix.platform }}-${{ matrix.arch }}.zip *

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resumemind-cli-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          *.tar.gz
          *.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          resumemind-cli-*/*.tar.gz
          resumemind-cli-*/*.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
